version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3307:3306"
    volumes:
      - data:/server/data
    environment:
      - MYSQL_ROOT_PASSWORD=Suporte99
      - MYSQL_DATABASE=db_tarefas
